# Generated by Django 4.1.7 on 2023-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('comprado', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
